[build]
  command = "npm run netlify-build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "./netlify-plugin-supabase-workaround.js"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200